version: "3"

networks:
  ding_bot:
    external: false

services:
    ding_bot:
        container_name: ding_bot
        networks:
          - ding_bot
        volumes:
            - ./config/:/app/config/
        image: registry.cn-hangzhou.aliyuncs.com/buyfakett/ding_bot:pg_db
  db:
      image: postgres:14.2
      restart: always
      container_name: ding_bot-db
      environment:
          - POSTGRES_USER=ding_bot
          - POSTGRES_PASSWORD=ding_bot
          - POSTGRES_DB=ding_bot
      networks:
          - ding_bot
      volumes:
          - ./postgres:/var/lib/postgresql/data
      ports:
          - "5432:5432"
